"""empty message

Revision ID: 7da9a36851d1
Revises: 7ba188c0c5a6
Create Date: 2017-08-31 19:42:38.120258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da9a36851d1'
down_revision = '7ba188c0c5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cbl_member', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('disabled', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_column('user', 'role_cbl')
    op.drop_column('user', 'role_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('role_cbl', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'disabled')
    op.drop_column('user', 'cbl_member')
    # ### end Alembic commands ###
