"""empty message

Revision ID: d98c8b29a698
Revises: 7da9a36851d1
Create Date: 2017-09-10 19:03:13.594694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98c8b29a698'
down_revision = '7da9a36851d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_access', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_access')
    # ### end Alembic commands ###
